//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabUsuario
    {
        public long CODIGO { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public Nullable<System.DateTime> dtUltimoAcess { get; set; }
        public System.DateTime dtCadastro { get; set; }
        public System.DateTime dtNascimento { get; set; }
    }
}
